version: '3'

services:
    db:
      build:
        context: ./mariadb
      volumes:
          - "./.data/db:/var/lib/mysql"
          - "./logs/mariadb:/var/log/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - default
    api:
      build:
        context: ./api
      depends_on:
        - db
      environment:
        - PORT=3000
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_HOST=${MYSQL_HOST}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
        - API_URL=http://${HOST}:3000
      ports:
        - 3000:3000
      command: npm start
      networks:
        - default
    frontend:
      build:
        context: ./frontend
      depends_on:
        - api
      environment:
        - PORT=8080
        - HOST=localhost
      command: npm run dev
      networks:
        - default
    browser:
      build:
        context: ./browser
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      networks:
        - default
networks:
  default:
    driver: bridge