version: '3'

services:
    db:
      build:
        context: ./mariadb
      volumes:
          - "./.data/db:/var/lib/mysql"
          - "./logs/mariadb:/var/log/mysql"
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - default
    api:
      build:
        context: ./api
      depends_on:
        - db
      volumes:
        - ./api:/var/www
      environment:
        - PORT=3000
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
        - API_URL=${API_URL}

      ports:
        - 3000:3000
      command: npm start
      networks:
        - default
networks:
  default:
    driver: bridge