version: '3'

services:
    api:
      build:
        context: ./api
      environment:
        - PORT=3000
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - API_URL=${API_URL}
        - MAX_PLACES=${MAX_PLACES}
        - AWS_REGION=${AWS_REGION}
        - AWS_DYNAMODB_ENDPOINT=${AWS_DYNAMODB_ENDPOINT}
      ports:
        - "3000:3000"
      command: npm start
      networks:
        - default
    frontend:
      build:
        context: ./frontend
      networks:
        - default
    browser:
      build:
        context: ./browser
        args:
          - SERVERLESS_VERSION=1.32.0
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - GRECAPTCHA_SITE_KEY=${GRECAPTCHA_SITE_KEY}
        - ANTICAPTCHA_KEY=${ANTICAPTCHA_KEY}
        - RUCAPTCHA_KEY=${RUCAPTCHA_KEY}
        - AWS_LAMBDA_MEMORY=${AWS_LAMBDA_MEMORY}
        - AWS_LAMBDA_TIMEOUT=${AWS_LAMBDA_TIMEOUT}
        - SLS_DEBUG=*
        - AWS_REGION=${AWS_REGION}
        - AWS_DYNAMODB_ENDPOINT=${AWS_DYNAMODB_ENDPOINT}
        - AWS_SQS_BROWSER_ARN=${AWS_SQS_BROWSER_ARN}
        - AWS_SQS_BROWSER_URL=${AWS_SQS_BROWSER_URL}
        - AWS_DYNAMODB_LAMBDAS_STREAM_ARN=${AWS_DYNAMODB_LAMBDAS_STREAM_ARN}
      networks:
        - default
    dispatcher:
      build:
        context: ./dispatcher
        args:
          - SERVERLESS_VERSION=1.32.0
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - SLS_DEBUG=*
        - AWS_REGION=${AWS_REGION}
        - AWS_DYNAMODB_ENDPOINT=${AWS_DYNAMODB_ENDPOINT}
        - AWS_SQS_BROWSER_ARN=${AWS_SQS_BROWSER_ARN}
        - AWS_SQS_BROWSER_URL=${AWS_SQS_BROWSER_URL}
        - AWS_SQS_DISPATCHER_ARN=${AWS_SQS_DISPATCHER_ARN}
        - AWS_SQS_DISPATCHER_URL=${AWS_SQS_DISPATCHER_URL}
        - MAX_PLACES=${MAX_PLACES}
        - AWS_LAMBDA_BATCH=${AWS_LAMBDA_BATCH}
      networks:
        - default
networks:
  default:
    driver: bridge