version: '3'

services:
    db:
      build:
        context: ./mariadb
      restart: always
      volumes:
          - "./.data/db:/var/lib/mysql"
          - "./logs/mariadb:/var/log/mysql"
        - PORT=3000
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE={MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - default
    api:
      build:
        context: ./api
      restart: always
      depends_on:
        - db
      environment:
        - PORT=3000
        - PORT=3000
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE={MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_HOST=${MYSQL_HOST}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
        - API_URL=${API_URL}
      ports:
        - 3000:3000
      command: npm start
      networks:
        - default
networks:
  default:
    driver: bridge